version: "3"

tasks:
  setup:
    desc: "Run cmake configuration"
    cmds:
      - cmake -S . -B build -G Ninja
  build:
    desc: "Run cmake build"
    cmds:
      - cmake --build build
  cook:
    desc: "Run cmake setup and build"
    cmds:
      - task: setup
      - task: build
  fmt:
    aliases: [clang-format, format]
    desc: "Run clang-format"
    dir: src
    cmds:
      - clang-format -i **/*.cpp **/*.hpp
  install:
    desc: "Run ninja install"
    cmds:
      - sudo ninja install -C build
  qdbus-gen:
    desc: "Generate qdbus adaptors"
    dir: src/backend/dbus
    cmds:
      - /usr/lib64/qt6/bin/qdbusxml2cpp -a generated/DisplayAdaptorGen schemas/DisplaySchema.Displays.xml
      - /usr/lib64/qt6/bin/qdbusxml2cpp -a generated/BatchSystemAdaptorGen schemas/DisplaySchema.BatchSystem.xml
      - /usr/lib64/qt6/bin/qdbusxml2cpp -a generated/OutputAdaptorGen schemas/DisplaySchema.Output.xml
      - /usr/lib64/qt6/bin/qdbusxml2cpp -a generated/OutputModeAdaptorGen schemas/DisplaySchema.OutputMode.xml