version: "3"

tasks:
  setup:
    desc: "Run cmake configuration"
    cmds:
      - cmake -S . -B build -G Ninja
  build:
    desc: "Run cmake build"
    cmds:
      - cmake --build build
  cook:
    desc: "Run cmake setup and build"
    cmds:
      - task: setup
      - task: build
  fmt:
    aliases: [clang-format, format]
    desc: "Run clang-format"
    dir: src
    cmds:
      - clang-format -i main.cpp **/*.{cpp,hpp}
  install:
    desc: "Run ninja install"
    cmds:
      - sudo ninja install -C build